server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: root
    password: mariadb
    url: r2dbc:mariadb://192.168.56.40:3306/polardb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

polar:
  catalog-service-uri: "http://localhost:9001"